server:
  host: localhost
  port: 8888
redis:
  network: tcp
  host: 127.0.0.1
  port: 6379
  password: 123456
  MaxIdle: 100
  MaxActive: 0
  IdleTimeout: 5m
  testFrequency: 1m
  Wait: true
  proxyPool: proxypool
  proxyInfo: proxyinfo
fetch:
  proxy: false
xicidaili:
  pages: 5
kuaidaili:
  pages: 5
ip3366:
  pages: 5
7yip:
  pages: 5
66ip:
  pages: 5
89ip:
  pages: 5
plphttp:
  pages: 5
plphttps:
  pages: 1