server:
  host: localhost
  port: 8888
redis:
  network: tcp
  host: 127.0.0.1
  port: 6379
  password: 123456
  MaxIdle: 100
  MaxActive: 0
  IdleTimeout: 5m
  testFrequency: 1m
  Wait: true
  proxyPool: proxypool
  proxyInfo: proxyinfo
fetch:
  proxy:
xicidaili:
  pages: 1
kuaidaili:
  pages: 5
proxylistplus:
  http:
    pages: 5
  https:
    pages: 1
ip3366:
  pages: 5